### ISSUE TITLE
Initial sync crashes.

### ISSUE THREAD

**Issue by presstab** [Veil-Project/veil#547]
GDB:
```
[Switching to Thread 0x7fffc57fa700 (LWP 27695)]
0x00007ffff564a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff564a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff564c02a in __GI_abort () at abort.c:89
#2  0x00007ffff568c7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff57a5ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff569537a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff57a5fa0 "double free or corruption (fasttop)", action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ffff569953c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00000000006b453a in __gnu_cxx::new_allocator<char>::deallocate (this=0x7fffac435a00, __p=<optimized out>) at /usr/include/c++/5/ext/new_allocator.h:110
#7  std::allocator_traits<std::allocator<char> >::deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/5/bits/alloc_traits.h:517
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x7fffac435a00)
    at /usr/include/c++/5/bits/basic_string.h:185
#9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7fffac435a00) at /usr/include/c++/5/bits/basic_string.h:180
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x7fffac435a00, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/basic_string.h:543
#11 std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~_List_node (this=0x7fffac4359f0, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/stl_list.h:106
#12 __gnu_cxx::new_allocator<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::destroy<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (this=<optimized out>, __p=0x7fffac4359f0) at /usr/include/c++/5/ext/new_allocator.h:124
#13 std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase (__position="`OA\254\377\177\000\000db21506c3c3f0f5e02e440be75ffbcac7bc31c590b65111cb5a11b82", this=0xfb3d00 <cacheValidatedPubcoin[abi:cxx11]>)
    at /usr/include/c++/5/bits/stl_list.h:1777
#14 std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::pop_back (this=0xfb3d00 <cacheValidatedPubcoin[abi:cxx11]>) at /usr/include/c++/5/bits/stl_list.h:1115
#15 LRUCacheTemplate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::set (value=true, key="", this=0xfb3d00 <cacheValidatedPubcoin[abi:cxx11]>)
    at ./veil/zerocoin/lrucache.h:59
#16 CheckZerocoinMint (txout=..., bnValue=..., state=..., fSkipZerocoinMintIsPrime=fSkipZerocoinMintIsPrime@entry=false) at consensus/tx_verify.cpp:255
#17 0x00000000006b47c2 in CheckStandardOutput (state=..., consensusParams=..., p=0x7fffa81a5440, nValueOut=@0x7fffc57f2448: 0, bnPubcoin=..., 
    fSkipZerocoinMintIsPrime=fSkipZerocoinMintIsPrime@entry=false) at consensus/tx_verify.cpp:278
#18 0x00000000006b5234 in CheckTransaction (tx=..., state=..., fSkipZerocoinMintIsPrime=fSkipZerocoinMintIsPrime@entry=false) at consensus/tx_verify.cpp:367
#19 0x0000000000614cfa in CheckBlock (block=..., state=..., consensusParams=..., fSkipComputation=fSkipComputation@entry=false, fCheckPOW=fCheckPOW@entry=true, 
    fCheckMerkleRoot=fCheckMerkleRoot@entry=true) at validation.cpp:3887
#20 0x000000000063da51 in ProcessNewBlock (chainparams=..., pblock=std::shared_ptr (count 2, weak 0) 0x7fffa854eaa0, fForceProcessing=fForceProcessing@entry=true, 
    fNewBlock=0x7fffc57f30d0, fNewBlock@entry=0xfae300 <cs_main>, fSkipComputation=fSkipComputation@entry=false) at validation.cpp:4570
#21 0x00000000004fa192 in ProcessMessage (enable_bip61=16, interruptMsgProc=..., connman=<optimized out>, chainparams=..., nTimeReceived=<optimized out>, vRecv=..., 
    strCommand=<error: Cannot access memory at address 0x839610b985300bb2>, pfrom=<optimized out>) at net_processing.cpp:3166
#22 PeerLogicValidation::ProcessMessages (this=<optimized out>, pfrom=<optimized out>, interruptMsgProc=...) at net_processing.cpp:3494
#23 0x00000000004a481d in CConnman::ThreadMessageHandler (this=0x1490d90) at net.cpp:2060
#24 0x0000000000461806 in std::function<void ()>::operator()() const (this=0x7fffc57f9eb0) at /usr/include/c++/5/functional:2267
#25 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (name=0xad30d4 "msghand", func=...) at ./util.h:377
#26 0x00000000004ba8db in std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (
    this=<optimized out>) at /usr/include/c++/5/functional:1531
#27 std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)>::operator()() (this=<optimized out>) at /usr/include/c++/5/functional:1520
#28 std::thread::_Impl<std::_Bind_simple<void (*(char const*, std::function<void ()>))(char const*, std::function<void ()>)> >::_M_run() (this=<optimized out>)
    at /usr/include/c++/5/thread:115
#29 0x00007ffff61d3c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#30 0x00007ffff59e66ba in start_thread (arg=0x7fffc57fa700) at pthread_create.c:333
#31 0x00007ffff571c41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Log End:
```
2019-04-29T01:31:30Z UpdateTip: new best=9dc9848cee4fe2ff1b8203c5e2c478269ed60ed25b4623b2839610b985300bb2 height=111725 type=PoW version=0x20000000 tx=327741 date='2019-03-23T14:03:29Z' cache=40.7MiB(253811txo)
2019-04-29T01:31:31Z UpdateTip: new best=dab8b6c9bea9a47fcea246baf78d45e42e53f4aa26c9d216c3202d6d6a14dafa height=111726 type=PoS version=0x20000000 tx=327743 date='2019-03-23T14:04:42Z' cache=40.7MiB(253813txo)
2019-04-29T01:31:31Z UpdateTip: new best=bb56c91d8dd52ee92609c8fda5cc8e3e0d8acf75c6d7c84e6c10e3c85356eba3 height=111727 type=PoS version=0x20000000 tx=327745 date='2019-03-23T14:04:58Z' cache=40.7MiB(253815txo)
```

**Comment by presstab** [comment]
It appears that this syncing issue/crash has several ways of being manifest. But what they all have in common is that they all stem from the LRUcaching in checkzerocoinmint.

**Comment by 4x13** [comment]
Since my other issue was close as being related to this one, and since my backtrace is a bit different, I will add them here in case they might help.

**Comment by 4x13** [comment]
![double free segfault - 1](https://user-images.githubusercontent.com/39984029/57117365-54bbaa00-6d10-11e9-8de6-112203612767.png)

![double free segfault - 2](https://user-images.githubusercontent.com/39984029/57117367-5b4a2180-6d10-11e9-86c2-a8b17461b609.png)
