### ISSUE TITLE
Segfault: Assertion `pindex' failed.

### ISSUE THREAD

**Issue by mimirmim** [Veil-Project/veil#701]
This was reported privately by 4x13, opening up an issue on his behalf with what information he gave me.

```PublicCoin::validate value is not prime
veil-qt: net_processing.cpp:3839: virtual bool PeerLogicValidation::SendMessages(CNode*): Assertion `pindex' failed.

Thread 37 "veil-msghand" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffee97fa700 (LWP 50354)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51        ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff2f22e97 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff2f24801 in __GI_abort () at abort.c:79
#2  0x00007ffff2f1439a in __assert_fail_base (fmt=0x7ffff309b7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555566a8861 "pindex", file=file@entry=0x555556657678 "net_processing.cpp", line=line@entry=3839, function=function@entry=0x555556659ba0 <PeerLogicValidation::SendMessages(CNode*)::__PRETTY_FUNCTION__> "virtual bool PeerLogicValidation::SendMessages(CNode*)")
    at assert.c:92
#3  0x00007ffff2f14412 in __GI___assert_fail (assertion=assertion@entry=0x5555566a8861 "pindex", file=file@entry=0x555556657678 "net_processing.cpp", line=line@entry=3839, function=function@entry=0x555556659ba0 <PeerLogicValidation::SendMessages(CNode*)::__PRETTY_FUNCTION__> "virtual bool PeerLogicValidation::SendMessages(CNode*)") at assert.c:101
#4  0x0000555555874d12 in PeerLogicValidation::SendMessages(CNode*) (this=0x7fffbc0585a0, pto=0x7fff20355030) at net_processing.cpp:3839
#5  0x000055555583d33e in CConnman::ThreadMessageHandler() (this=0x7fffbe69a830) at net.cpp:2067
#6  0x000055555580109e in std::function<void ()>::operator()() const (this=0x7ffee97f9990) at /usr/include/c++/7/bits/std_function.h:706
#7  0x000055555580109e in TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (name=<optimized out>, func=...) at ./util.h:377
#8  0x0000555555852a8b in std::__invoke_impl<void, void (*)(char const*, std::fu---Type <return> to continue, or q <return> to quit---
nction<void ()>), char const*, std::function<void ()> >(std::__invoke_other, void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__f=<optimized out>) at /usr/include/c++/7/bits/invoke.h:60
#9  0x0000555555852a8b in std::__invoke<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__fn=<optimized out>)
    at /usr/include/c++/7/bits/invoke.h:95
#10 0x0000555555852a8b in std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#11 0x0000555555852a8b in std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::operator()() (this=<optimized out>) at /usr/include/c++/7/thread:243
#12 0x0000555555852a8b in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > > >::_M_run() (this=<optimized out>) at /usr/include/c++/7/thread:186
#13 0x00007ffff394866f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff4d646db in start_thread (arg=0x7ffee97fa700)
    at pthread_create.c:463
#15 0x00007ffff300588f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by sinetek** [comment]
Sounds a bit like internal db corruption.  Bitcoin has the same assert in that position.

**Comment by mimirmim** [comment]
Thanks @sinetek I think you are right.
